apiVersion: v1
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://message-postgresql:5432/message
    spring.datasource.username=message
    spring.datasource.password=message
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.jpa.hibernate.ddl-auto=create
kind: ConfigMap
metadata:
  name: message-app-config