apiVersion: v1
kind: Template
metadata:
  name: message-service-v2-template
  annotations:
    description: "Description"
parameters:
labels:
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: message-v2
      group: com.yourcompany.newapp
      provider: fabric8
      version: 1.0.0
    name: message-v2
  spec:
    lookupPolicy:
      local: true
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: message-v2
      expose: "true"
      group: com.yourcompany.newapp
      provider: fabric8
      version: 1.0.0
    name: message-v2
  spec:
    host: message-v2-hello-world.apps.nantes-30d4.openshiftworkshop.com
    port:
      targetPort: 8080
    to:
      kind: Service
      name: message-v2
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-branch: v2
      fabric8.io/git-commit: 4f4a4d80ac6756f56c21ef6208832402418d0479
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/message-v2
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/message-v2
      fabric8.io/scm-tag: booster-parent-23
      fabric8.io/scm-url: https://github.com/openshiftio/message-v2
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: message-v2
      expose: "true"
      group: com.yourcompany.newapp
      module: message
      provider: fabric8
      version: 1.0.0
    name: message-v2
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: message-v2
      group: com.yourcompany.newapp
      provider: fabric8
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-branch: v2
      fabric8.io/git-commit: 4f4a4d80ac6756f56c21ef6208832402418d0479
      fabric8.io/iconUrl: img/icons/spring-boot.svg
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=message-v2&var-version=1.0.0
      fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/message-v2
      fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/message-v2
      fabric8.io/scm-tag: booster-parent-23
      fabric8.io/scm-url: https://github.com/openshiftio/message-v2
    labels:
      app: message-v2
      group: com.yourcompany.newapp
      module: message
      provider: fabric8
      version: 1.0.0
    name: message-v2
  spec:
    replicas: 1
    selector:
      app: message-v2
      group: com.yourcompany.newapp
      provider: fabric8
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-branch: v2
          fabric8.io/git-commit: 4f4a4d80ac6756f56c21ef6208832402418d0479
          fabric8.io/iconUrl: img/icons/spring-boot.svg
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=message-v2&var-version=1.0.0
          fabric8.io/scm-con-url: scm:git:https://github.com/openshiftio/booster-parent.git/message-v2
          fabric8.io/scm-devcon-url: scm:git:git:@github.com:openshiftio/booster-parent.git/message-v2
          fabric8.io/scm-tag: booster-parent-23
          fabric8.io/scm-url: https://github.com/openshiftio/message-v2
        labels:
          app: message-v2
          group: com.yourcompany.newapp
          module: message
          provider: fabric8
          version: 1.0.0
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: message-v2:latest
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: message-v2
      group: com.yourcompany.newapp
      provider: fabric8
      version: 1.0.0
    name: message-v2-s2i
  spec:
    nodeSelector: {}
    output:
      to:
        kind: ImageStreamTag
        name: message-v2:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: v2
        uri: 'https://github.com/hello-world-msa-demo/message-service.git'
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS
          value: '-Popenshift-it'
        from:
          kind: DockerImage
          name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.6
      type: Source
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
- apiVersion: v1
  data:
    application.properties: |
      spring.datasource.url=jdbc:postgresql://message-postgresql:5432/message
      spring.datasource.username=message
      spring.datasource.password=message
      spring.datasource.driver-class-name=org.postgresql.Driver
  kind: ConfigMap
  metadata:
    labels:
      app: message-v2
      group: com.yourcompany.newapp
      provider: fabric8
      version: 1.0.0
    name: message-app-config
